#! /bin/sh
### BEGIN INIT INFO
# Provides:        opi_dnsupdate 
# Required-Start:  $network $local_fs
# Required-Stop: 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Triggers updates of singed certificates
# Description: 
### END INIT INFO

# Author: PA Nilsson <pa@openproducts.se>

. /lib/lsb/init-functions

do_start() {
	echo "Requesting update of signed certificates"
    /usr/share/opi-access/dns_update.py
    echo "Running UPNP script"
    /usr/share/opi-access/opi-access.sh
}

do_stop() {
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
